version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.2
    steps:
      - checkout
      - run: echo "bye world"
      - run: cat text.txt

workflows:
  version: 2
  build:
    jobs:
      - build
